stages:
    - test

variables:
    TENJIN_TESTING: "yes"

before_script:
    - yum install -y epel-release
    - yum install -y python-pip gcc python-devel
    - pip install flake8
    - pip install --upgrade setuptools
    - flake8 --version

python_flake8:
    stage: test
    tags:
        - python
    script:
        - find . -type f -name '*.py' |xargs -r flake8
        - find . -type f -executable -a ! -path './.git/*' -exec grep -q '/usr/bin/env python' '{}' \; -print0 |xargs -0 -r flake8

